#include<iostream>
#include<fstream>
using namespace std;
#include"Lexer.h"
#include"Parser.h"



void LexerInit(string* fileArgs)
{
	Lexer lexer;							//Instantiating lexer object.
	lexer.init(fileArgs);					//Initializing lexer with files containg keywords,operators and such.
	lexer.initMap("map.txt");				//Initialzing  the key-value map of symbol-index values.
	lexer.GetTokens("input.txt");			//Get tokens function is passed a file and it populates the following:
											//1 . symbolTable.txt (containing symbol table entries)
											//2 . tokens.txt (containing tokens)
											//3 . errors.txt (containing errors) 
}

void ParserInit(string* fileArgs) {

	Parser parser;							//Instantiating parser object.
	parser.init(fileArgs);					//Initializing parser with relevent files.
	parser.initLog("parselog.txt");			//Setting parser to generate a log file containing parsing
	parser.parse();							//calling parse(), this will start parsing the tokens.txt generated by lexer object.
											//log maintained in parserlog.txt
}

// INPUT.TXT  ->  LEXER OBJECT -> TOKENS.TXT + symboltable.txt  -> PARSER OBJECT -> PARSELOG.TXT
int main()
{
	string fileArgs[] = { "keywords.txt","Operators.txt","Punctuation.txt","mapping.txt" };
	LexerInit(fileArgs);

	string fileNames[] = { "cfg.txt","parsetable.txt","cfgmap.txt","tokens.txt","symbolTable.txt","terminals.txt"};
	ParserInit(fileNames);

	return 0;
}